### ISSUE TITLE
refactor: remove `moment` package

### ISSUE THREAD

**Issue by erfanium** [erfanium/my-irancell-cli#2]
moment package could be replaced by few line of code

**Comment by MadGanGithub** [comment]
Hi Erfan,
 I'd like to work on this issue. Can you please assign it to me?

**Comment by erfanium** [comment]
@MadGanGithub sure

**Comment by MadGanGithub** [comment]
Can you provide a dummy account credentials for testing purpose? As I'm from India, I can't create an account

**Comment by erfanium** [comment]
@MadGanGithub I don't have any dummy accounts right now. but I can test it for your. open a PR

**Comment by MadGanGithub** [comment]
Done 👍

**Comment by MadGanGithub** [comment]
@erfanium is there anything else to be sorted out?
If not, this can be closed right?

**Comment by erfanium** [comment]
@MadGanGithub yeah, thanks for the help!
